spring:
  application:
    name: GATEWAY-SERVICE

server:
  port: 5000

eureka:
  instances:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/